import { Product, Category, Collection, Review, Coupon, StoreSettings } from "@/types";

export const initialCategories: Category[] = [
  {
    id: "cat-1",
    name: "Luxury Tees",
    slug: "luxury-tees",
    description: "260 GSM Heavyweight Combed Cotton Tees with 3D Raised Gold Monogram Branding.",
    image_url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 1,
  },
  {
    id: "cat-2",
    name: "Prestige Drops",
    slug: "prestige-drops",
    description: "Limited Run Collections & Exclusive Minimalist Streetwear.",
    image_url: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 2,
  },
  {
    id: "cat-3",
    name: "Heavyweight Hoodies",
    slug: "heavyweight-hoodies",
    description: "350 GSM Fleece Luxury Comfort Hoodies.",
    image_url: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 3,
  },
];

export const initialCollections: Collection[] = [
  {
    id: "col-1",
    name: "Drop #1 — Timeless Essentials",
    slug: "drop-1-timeless-essentials",
    description: "Our signature 260 GSM debut collection featuring 3D raised gold monogram craftsmanship.",
    image_url: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "col-2",
    name: "Minimalist Prestige",
    slug: "minimalist-prestige",
    description: "Clean silhouettes engineered for everyday bold luxury.",
    image_url: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&auto=format&fit=crop&q=80",
    is_featured: true,
    is_active: true,
    sort_order: 2,
  },
];

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "AYVO 3D Gold Monogram Jet Black Luxury Tee",
    slug: "ayvo-3d-gold-monogram-jet-black-tee",
    short_description: "Signature 260 GSM Heavyweight Combed Cotton Tee with 3D Raised Gold Monogram.",
    description: `Elevate your daily wardrobe with the AYVO 3D Gold Monogram Jet Black Luxury Tee. Engineered from premium 260 GSM combed cotton, this piece combines structural drape with ultra-soft breathability. Features our custom-designed 3D raised gold monogram logo heat-transferred on the left chest for a subtle yet unmissable tactile luxury statement.
    
• 260 GSM Heavyweight 100% Combed Cotton
• High-density 3D Raised Gold Monogram
• Ribbed collar with shape-retention elastane
• Pre-shrunk fabric to prevent post-wash shrinkage
• Designed in Karachi, Pakistan`,
    price: 3999,
    sale_price: 2999,
    compare_price: 3999,
    sku: "AYVO-TEE-BLK-01",
    stock_quantity: 45,
    low_stock_threshold: 10,
    weight_grams: 260,
    status: "published",
    is_featured: true,
    is_trending: true,
    is_new_arrival: true,
    is_best_seller: true,
    tags: ["260 GSM", "Gold Monogram", "Black Tee", "Luxury Essential"],
    category_id: "cat-1",
    collection_id: "col-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img-1",
        product_id: "prod-1",
        image_url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&auto=format&fit=crop&q=80",
        is_thumbnail: true,
        sort_order: 1,
        alt_text: "AYVO Jet Black Gold Monogram Tee Front",
      },
      {
        id: "img-2",
        product_id: "prod-1",
        image_url: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=1000&auto=format&fit=crop&q=80",
        is_thumbnail: false,
        sort_order: 2,
        alt_text: "AYVO Jet Black Gold Monogram Tee Back View",
      },
    ],
    variants: [
      { id: "v-1", product_id: "prod-1", size: "S", stock_quantity: 10, price_adjustment: 0, sku_variant: "AYVO-TEE-BLK-S" },
      { id: "v-2", product_id: "prod-1", size: "M", stock_quantity: 15, price_adjustment: 0, sku_variant: "AYVO-TEE-BLK-M" },
      { id: "v-3", product_id: "prod-1", size: "L", stock_quantity: 12, price_adjustment: 0, sku_variant: "AYVO-TEE-BLK-L" },
      { id: "v-4", product_id: "prod-1", size: "XL", stock_quantity: 8, price_adjustment: 0, sku_variant: "AYVO-TEE-BLK-XL" },
    ],
  },
  {
    id: "prod-2",
    name: "AYVO Minimal Off-White Gold Emblem Tee",
    slug: "ayvo-minimal-off-white-gold-emblem-tee",
    short_description: "Off-white minimal luxury 260 GSM tee with gold metallic emblem.",
    description: `A masterclass in modern minimalism. The AYVO Off-White Gold Emblem Tee is crafted from rich cream 260 GSM fabric, offering effortless structure and year-round comfort. Adorned with our iconic gold monogram.
    
• 260 GSM Premium Heavyweight Cotton
• Clean minimal tailored silhouette
• Reinforced double-needle stitching on hem & sleeves
• Pre-washed for a buttery hand-feel`,
    price: 3999,
    sale_price: 2999,
    compare_price: 3999,
    sku: "AYVO-TEE-WHT-02",
    stock_quantity: 30,
    low_stock_threshold: 8,
    weight_grams: 260,
    status: "published",
    is_featured: true,
    is_trending: true,
    is_new_arrival: true,
    is_best_seller: false,
    tags: ["260 GSM", "Off-White", "Gold Monogram", "Minimal"],
    category_id: "cat-1",
    collection_id: "col-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img-3",
        product_id: "prod-2",
        image_url: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=1000&auto=format&fit=crop&q=80",
        is_thumbnail: true,
        sort_order: 1,
        alt_text: "AYVO Off-White Gold Emblem Tee Front",
      },
    ],
    variants: [
      { id: "v-5", product_id: "prod-2", size: "S", stock_quantity: 8, price_adjustment: 0, sku_variant: "AYVO-TEE-WHT-S" },
      { id: "v-6", product_id: "prod-2", size: "M", stock_quantity: 12, price_adjustment: 0, sku_variant: "AYVO-TEE-WHT-M" },
      { id: "v-7", product_id: "prod-2", size: "L", stock_quantity: 10, price_adjustment: 0, sku_variant: "AYVO-TEE-WHT-L" },
    ],
  },
  {
    id: "prod-3",
    name: "AYVO Prestige Boxed Gift Set (Tee + Box + Card)",
    slug: "ayvo-prestige-boxed-gift-set",
    short_description: "Luxury matte black gold-embossed box packaging with 260 GSM Tee & Thank You card.",
    description: `Experience unboxing at its finest. The AYVO Prestige Boxed Gift Set includes our signature 260 GSM Tee presented inside a custom matte black luxury box with gold foil stamping and an acrylic thank you card.
    
• Includes 1x AYVO 260 GSM Tee (Black or White)
• Custom AYVO Rigid Luxury Magnetic Box
• Custom Gold Embossed Thank You Card
• Ideal for gifting or personal collection`,
    price: 4999,
    sale_price: 3999,
    compare_price: 4999,
    sku: "AYVO-GIFT-03",
    stock_quantity: 20,
    low_stock_threshold: 5,
    weight_grams: 500,
    status: "published",
    is_featured: true,
    is_trending: false,
    is_new_arrival: true,
    is_best_seller: true,
    tags: ["Gift Box", "Luxury Packaging", "Limited Edition"],
    category_id: "cat-2",
    collection_id: "col-2",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img-4",
        product_id: "prod-3",
        image_url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1000&auto=format&fit=crop&q=80",
        is_thumbnail: true,
        sort_order: 1,
        alt_text: "AYVO Luxury Gift Box Packaging",
      },
    ],
    variants: [
      { id: "v-8", product_id: "prod-3", size: "M", stock_quantity: 10, price_adjustment: 0, sku_variant: "AYVO-GIFT-M" },
      { id: "v-9", product_id: "prod-3", size: "L", stock_quantity: 10, price_adjustment: 0, sku_variant: "AYVO-GIFT-L" },
    ],
  },
  {
    id: "prod-4",
    name: "AYVO Drop #1 Limited Edition Dual Pack",
    slug: "ayvo-drop-1-limited-edition-dual-pack",
    short_description: "Both Jet Black & Off-White 260 GSM Luxury Tees bundled together.",
    description: `Complete your wardrobe with both colorways from Drop #1. Bundle includes 1x Jet Black 3D Gold Tee and 1x Off-White Gold Emblem Tee at a special drop discount.`,
    price: 7999,
    sale_price: 5499,
    compare_price: 7999,
    sku: "AYVO-BUNDLE-04",
    stock_quantity: 15,
    low_stock_threshold: 3,
    weight_grams: 520,
    status: "published",
    is_featured: true,
    is_trending: true,
    is_new_arrival: true,
    is_best_seller: true,
    tags: ["Bundle", "Drop #1", "Special Price"],
    category_id: "cat-2",
    collection_id: "col-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img-5",
        product_id: "prod-4",
        image_url: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1000&auto=format&fit=crop&q=80",
        is_thumbnail: true,
        sort_order: 1,
        alt_text: "AYVO Dual Pack Tees",
      },
    ],
    variants: [
      { id: "v-10", product_id: "prod-4", size: "M", stock_quantity: 8, price_adjustment: 0, sku_variant: "AYVO-BNDL-M" },
      { id: "v-11", product_id: "prod-4", size: "L", stock_quantity: 7, price_adjustment: 0, sku_variant: "AYVO-BNDL-L" },
    ],
  },
];

export const initialReviews: Review[] = [
  {
    id: "rev-1",
    product_id: "prod-1",
    customer_name: "Hamza K.",
    rating: 5,
    title: "Unbelievable 260 GSM quality!",
    body: "Honestly blown away by the fabric density and the 3D gold logo feel. It feels exactly like my high-end streetwear items from Dubai. 10/10 recommend!",
    status: "approved",
    is_verified_buyer: true,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "rev-2",
    product_id: "prod-1",
    customer_name: "Shahzaib M.",
    rating: 5,
    title: "Packaging is next level",
    body: "Ordered via WhatsApp and received it in Karachi within 2 days. Unboxing felt extremely premium with the matte black box.",
    status: "approved",
    is_verified_buyer: true,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "rev-3",
    product_id: "prod-2",
    customer_name: "Usman A.",
    rating: 5,
    title: "Perfect boxy fit",
    body: "The off-white color is gorgeous and non-see-through because of the 260 GSM weight. Will definitely buy from Drop #2.",
    status: "approved",
    is_verified_buyer: true,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];

export const initialStoreSettings: StoreSettings = {
  id: "setting-1",
  store_name: "AYVO",
  store_email: "contact@ayvo.pk",
  store_phone: "+92 371 0108284",
  whatsapp_number: "923710108284",
  store_address: "Karachi, Pakistan",
  currency: "PKR",
  currency_symbol: "Rs.",
  logo_url: "/logo.png",
  favicon_url: "/favicon.ico",
  primary_color: "#0D0D0D",
  accent_color: "#C9A44C",
  instagram_url: "https://instagram.com/ayvo_official110",
  facebook_url: "https://facebook.com/ayvo.official",
  tiktok_url: "https://tiktok.com/@ayvo_official",
  shipping_policy: "Free standard delivery across Pakistan on orders above Rs. 4,999. Orders delivered within 3-5 working days.",
  return_policy: "7-day hassle-free exchange & return policy for unworn items in original packaging.",
  privacy_policy: "We safeguard all personal information with enterprise-grade encryption.",
  terms_conditions: "All orders subject to product availability.",
  tax_rate: 0,
  free_shipping_above: 4999,
  updated_at: new Date().toISOString(),
};
